baseURL = "https://rla4.github.io/"
languageCode = "pt-br"
title = "Roberta Arcoverde"
theme = "imadesigner"

[params]
    github = "https://github.com/rla4"
    twitter = "https://twitter.com/rla4"
    stackoverflow = "https://stackoverflow.com/users/411343"
    linkedin = "https://www.linkedin.com/in/robertaarcoverde/"

[author]
    name = "roberta arcoverde"

[taxonomies]
  tag = "tags"    